[package]
name = "tower-rate-limiter-redis"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tower-rate-limiter-redis"
path = "src/main.rs"

[dependencies]
axum = "0.7.5"
http = "1.1.0"
pin-project = "1.1.5"
tokio = { version = "1.37.0", features = ["full"] }
tower = "0.4.13"
